### ISSUE TITLE
enry treats Protobuf as PureBasic

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/enry#100]
Any `*.pb` file in protobuf format is detected as PureBasic in the most recent release 1.4.

**Comment by abeaumont** [comment]
So does `linguist`, if I'm not mistaken.

**Comment by vmarkovtsev** [comment]
Nopes.

```
linguist .
100.00% Python
```

**Comment by abeaumont** [comment]
Weird, considering that, for example, [libuast](https://github.com/bblfsh/libuast) is considered `86.9% PureBasic`... and I can reproduce it with cli `linguist`:

```
$ linguist .
86.87%  PureBasic
6.68%   Python
5.47%   Java
0.48%   C
0.35%   C++
0.12%   CMake
0.02%   Go
0.01%   Shell
```

What repo and `pb` files are you testing?

**Comment by vmarkovtsev** [comment]
I can reproduce it on libuast repo too. I used the local version of src-d/ast2vec with a committed pb file.

**Comment by vmarkovtsev** [comment]
https://github.com/github/linguist/issues/3816

**Comment by vmarkovtsev** [comment]
@abeaumont As noted in the linked issue, there are [override files](https://github.com/github/linguist#overrides). Does enry support them?

**Comment by abeaumont** [comment]
@vmarkovtsev No, it doesn't. There's an issue and a PR for that feature, but it requires some non-trivial changes and it's not expected to be done anytime soon.

**Comment by abeaumont** [comment]
It seems to be working properly now:

```
> enry
79.31%	Python
10.34%	Protocol Buffer
3.45%	C
3.45%	Text
3.45%	Makefile
```

**Comment by vmarkovtsev** [comment]
Cool! But what has changed?

**Comment by abeaumont** [comment]
I guess `linguist` got fixed: https://github.com/src-d/enry/pull/118/files#diff-2dd48c23213b4dde1b5c99ba45fc9086L321
