### ISSUE TITLE
Review, document and release `enry` including `enry-java`

### ISSUE THREAD

**Issue by abeaumont** [src-d/enry#102]

**Comment by erizocosmico** [comment]
http://www.sonatype.org/nexus/2015/06/02/how-to-publish-software-artifacts-to-maven-central/
https://alexn.org/blog/2017/08/16/automatic-releases-sbt-travis.html
https://leonard.io/blog/2017/01/an-in-depth-guide-to-deploying-to-maven-central/
http://www.scala-sbt.org/sbt-pgp/usage.html

Code ready in https://github.com/erizocosmico/enry/tree/feature/maven-publish-jar

Missing things:

* apply on sonatype to have the repo added
* source{d} account username and password for sonatype
* new source{d} GPG key (ecrypted for travis) (https://docs.travis-ci.com/user/encrypting-files/)
* actually publish one release after all this is done

**Comment by abeaumont** [comment]
Project request at https://issues.sonatype.org/browse/OSSRH-34579

**Comment by abeaumont** [comment]
Project has been accepted.

**Comment by bzz** [comment]
One thing to note is - we need to make sure that final artifact that is published, is produced by `./sbt assembly` which is a fatJar with all the dependencies inside, and not the one produced by `./sbt package` (will not include native deps inside).

**Comment by abeaumont** [comment]
`enry-java` published en maven central: http://search.maven.org/#artifactdetails%7Ctech.sourced%7Cenry-java%7C1.0.0%7Cjar

Please let me know if you find any problem.

**Comment by abeaumont** [comment]
I'd like to add this information to the README.md in the `java` subdir, could you help me with the correct wording to indicate how this dependency can be handled through maven central in the java ecosystem @ajnavarro?

**Comment by ajnavarro** [comment]
http://search.maven.org/#artifactdetails%7Ctech.sourced%7Cenry-java%7C1.0.0%7Cjar

At the bottom left you have how to add the dependency to maven and to sbt, the two more common dependency management systems for the JVM.

**Comment by abeaumont** [comment]
Just released `v1.5.1` of both `enry` and `enry-java`. I consider this done, if you find anything missing, feel free to reopen it.
