### ISSUE TITLE
The results differ from linguist much

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/enry#110]
```
sourced@sourced-MacBookPro:/tmp$ git clone https://github.com/src-d/enry &>/dev/null
sourced@sourced-MacBookPro:/tmp$ cd enry
sourced@sourced-MacBookPro:/tmp/enry$ time linguist
99.25%  Go
0.35%   Shell
0.24%   Java
0.08%   Ruby
0.05%   Makefile
0.01%   Scala
0.01%   Gnuplot

real    0m1.945s
user    0m1.848s
sys    0m0.056s
sourced@sourced-MacBookPro:/tmp/enry$ time /home/sourced/Projects/ast2vec/enry 
3.28%    Makefile
63.93%    Go
9.84%    CSV
6.56%    Shell
1.64%    Gnuplot
1.64%    Text
3.28%    Ruby
3.28%    Scala
6.56%    Java

real    0m0.084s
user    0m0.072s
sys    0m0.008s
```

**Comment by abeaumont** [comment]
Thanks for reporting @vmarkovtsev.
`linguist` uses number of bytes to get these stats, while `enry` uses number of files.
We could change it at some point to make it compatible.

**Comment by vmarkovtsev** [comment]
Aaa, this explains a lot! Thanks.

**Comment by abeaumont** [comment]
@mcuadros should we work on this compatibility mode, what do you think?

**Comment by bzz** [comment]
Opt-in compatibility mode would make a lot of sense.

**Comment by vmarkovtsev** [comment]
+1 this. IMHO there should be three modes: number of files, number of lines and number of bytes. All three metrics are used in the scientific papers.

**Comment by zkry** [comment]
Hello, I'd like to work on this 🙂. I created a PR with two flags to improve compatibility with linguist.

The first one is `mode` where you can select byte, file or line and have the files be counted accordingly.

I also noticed that by default linguist excludes non-programming languages so I created a simple flag that does this.

Unfortunately the two commands are not 100% the same as linguist seems to ignore some files. For example on the github.com/istio/istio project, enry counts this file  https://raw.githubusercontent.com/istio/istio/master/addons/servicegraph/js/viz/viz-lite.js while linguist skips it making their results differ a lot.

**Comment by vmarkovtsev** [comment]
That's very cool @zkry 

Regarding the skipped files, we are having a dedicated project with our intern since March to filter unwanted data. Feel free to comment! https://docs.google.com/document/d/1_S2tEYain5vssEgVH5zGCnbiptW-w82I-3j8GMUnrzA

**Comment by zkry** [comment]
Nice, looks interesting! I'll take a look at that.

**Comment by campoy** [comment]
Any news on this? Was this implemented?

**Comment by sfwn** [comment]
@campoy already. you can try.

```
$ enry --help                                                                                                                                                    [17:44:18]
  enry undefined build: undefined commit: undefined, based on linguist commit: 4cd558c
  enry, A simple (and faster) implementation of github/linguist
  usage: enry [-mode=(file|line|byte)] [-prog] <path>
         enry [-mode=(file|line|byte)] [-prog] [-json] [-breakdown] <path>
         enry [-mode=(file|line|byte)] [-prog] [-json] [-breakdown]
         enry [-version]
```

**Comment by smola** [comment]
I assume this was fixed then.

**Comment by abdennour** [comment]
Yes @smola ! just let people know to use `-mode` option to switch among 3 values: byte, file or line
