### ISSUE TITLE
Question: GetLanguageByContent

### ISSUE THREAD

**Issue by cxww107** [src-d/enry#136]
Hi, 

I'd like to use your library to detect the programming language from user input. So I won't have a file extension.  I only have a string with source code. Can I achieve my goal using this project? 

Thanks.

Nikolay

**Comment by abeaumont** [comment]
Unfortunately not, currently language by content heuristic is only applied to a (small) list of possible candidates filtered from language extension, not in a generic way. So adding such support is far from trivial. You can look at https://github.com/src-d/enry/blob/3a78601f6ec1014745af0475230bd195ee894ee1/common.go#L396-L397 for details
