### ISSUE TITLE
Support (bare) git repositories

### ISSUE THREAD

**Issue by ZJvandeWeg** [src-d/enry#141]
Right now enry works on checked out repositories. However, the project it was ported from linguist does work on git repositories.

Advantages of supporting this include that files matching`.gitignore` are skipped and it works on repositories that are bare. The git driver could be go-git or shell outs. The latter option would require a git binary however.

**Comment by vmarkovtsev** [comment]
The API is pretty much Git agnostic, so this proposal targets the command line application. Currently AFAIK `enry` ignores Git existence completely. I am +1 to make `enry` closer to `linguist` but we are currently in maintenance mode, so contributions welcome!
@juanjux @dennwc You are the real maintainers :)

**Comment by vmarkovtsev** [comment]
@ZJvandeWeg It is [semana santa](https://en.wikipedia.org/wiki/Holy_Week#Spain) in Spain so most likely you'll get an official response on Monday.

**Comment by ZJvandeWeg** [comment]
@vmarkovtsev I think the interface needs to change though. One example:

https://github.com/src-d/enry/blob/abdfc77dbcd2d6e2fda05f139b0f6d6d56cc46b1/common.go#L37-L40

I think it would be better to have a `io.Reader` or something like it. This would allow for not reading content at all if some strategies were swapped around.

> we are currently in maintenance mode, so contributions welcome!

What does this mean, exactly?

**Comment by vmarkovtsev** [comment]
Regarding the mode statement, this means that we've implemented everything we need for our production, it works like a charm and adding new features is not our priority. However, we are happy to review and merge contributions from community.

**Comment by campoy** [comment]
Closing this issue since there has not been any updates in over a month.

We accept pull requests if anyone wants to implement this feature, I'll be happy to review it.
Alternatively it'd be quite easy to build a new tool that uses enry to analyze git repositories.
