### ISSUE TITLE
Update or remove benchmarks from README

### ISSUE THREAD

**Issue by mcuadros** [src-d/enry#149]
Since we got a 2x performance in the new version, we should update the README.md, or remove it.

**Comment by Soundug** [comment]
Hi @mcuadros! Is this issue still open?
I would like to work on this.

**Comment by bzz** [comment]
Hey @Soundug - yes, it very much is!

The best approach is to re-run existing benchmark with the latest release of Enry and update the Readme with results.

**Comment by bzz** [comment]
Latest comparison results using existing benchmark posted in #184
