### ISSUE TITLE
undefined: sort.Slice when using go get

### ISSUE THREAD

**Issue by wangpeipei90** [src-d/enry#151]
Here is the error: 
```
user@vm:~$ go get gopkg.in/src-d/enry.v1/...
# gopkg.in/src-d/enry.v1/cmd/enry
go/src/gopkg.in/src-d/enry.v1/cmd/enry/main.go:213: undefined: sort.Slice
```
The cmd is executed on Ubuntu 16.04.4 LTS, a VM with linux kernel 4.4.0-124-generic

**Comment by vmarkovtsev** [comment]
@wangpeipei90 what's your `go version`

**Comment by wangpeipei90** [comment]
go version go1.6.2 linux/amd64

**Comment by vmarkovtsev** [comment]
We support 1.9+

Your version is too outdated, e.g. `sort.Slice` appeared in 1.8.
