### ISSUE TITLE
Upload latest version to maven

### ISSUE THREAD

**Issue by mcarmonaa** [src-d/enry#158]
Last version available in maven is `1.6.3` but the latest one is `1.6.5` https://search.maven.org/search?q=g:tech.sourced%20AND%20a:enry-java&core=gav

**Comment by bzz** [comment]
Thank you! Seems like may be a bug in release process somewhere 🤔

**Comment by bzz** [comment]
Indeed https://github.com/src-d/enry/blob/master/java/build.sbt#L3 the Java artefact version is 1.6.3

**Comment by bzz** [comment]
CI is slow today, but release build is in progress https://travis-ci.org/src-d/enry/builds/442671176

**Comment by bzz** [comment]
CI seemed to pass, but maven.org is now down 😕 
<img width="863" alt="screen shot 2018-10-17 at 10 26 22 pm" src="https://user-images.githubusercontent.com/5582506/47111622-b2007a00-d25c-11e8-8ef9-3fe10d3777da.png">

**Comment by bzz** [comment]
🎉 https://search.maven.org/artifact/tech.sourced/enry-java/1.6.6/jar
