### ISSUE TITLE
Java: automate getting version from the tag on CI

### ISSUE THREAD

**Issue by bzz** [src-d/enry#163]
Right now for java release artifacts we use hard-coded version number.

That is allright but is prone to errors like #158.

To avoid this, we should have an automation that fetches version number from Git tag on CI, as we do for Go in src-d/ci.

This can be done using `com.typesafe.sbt:sbt-git` as in https://github.com/src-d/jgit-spark-connector/blob/master/build.sbt#L11 from https://github.com/src-d/jgit-spark-connector/issues/146

**Comment by pratik97** [comment]
I would like to take this issue. Can you provide some more information like in which files I should make changes?

**Comment by bzz** [comment]
Closing as #165 was merged and https://github.com/src-d/enry/releases/tag/v1.6.7 released
