### ISSUE TITLE
Bazel files misclassified as Python

### ISSUE THREAD

**Issue by campoy** [src-d/enry#182]
As part of the [kubernetes analysis](https://docs.google.com/presentation/d/e/2PACX-1vTAqb7XSLN42hJLSWhO3uFm1rklkJ2b_m5Lk_ExhLE37IZ0ZWNDFZQvwVNUQOdrSrqlrV3K1n7QERWf/pub?start=false&loop=false&delayms=3000) we analyzed all of the languages in the kubernetes codebase:

We found Python reappearing during 2017 but after a deeper analysis it turns out those are all `BUILD` files with [Bazel](https://bazel.build/) content.

For instance, github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/discovery/https/BUILD appears as Python while it's actually Bazel.

This mistake is also done by linguist, as shown [here](https://github.com/kubernetes/kubernetes/search?l=python)

**Comment by creachadair** [comment]
For BUILD files, the tool could presumably check the filename—if it looks like Python and is named `BUILD`, `BUILD.bazel`, or `WORKSPACE`, then it's probably a Bazel file.

But Starlark also occurs in https://github.com/google/copybara, and will probably start to infect other tools over time. So I guess the question is to what extent is it important to always get this right, vs. catching the common cases?

**Comment by campoy** [comment]
That's a good question, indeed.

Maybe the way it is now is already ok since Skylark is a dialect of Python.
Unless there's a very obvious way to detect it's indeed Skylark and not Python?

**Comment by creachadair** [comment]
There are a few shibboleths one could look for: `load("[^"]", …)` combined with lack of any `import` statements. Use of `depset`. Left-justified function calls with nothing after the opening bracket (for rules):

```
cc_library(
  name = "…",
```

and so on. Some of those would be reasonably easy to automate with regular expressions, but I'm not sure how far down that rabbit hole we need to go.

**Comment by creachadair** [comment]
But if precision isn't crucial, you could more simply say:

* If it looks like Python,
   - If the filename is `BUILD` or matches `*.bzl`, it's Bazel.
   - Otherwise if the filename matches `*.sky` it's some other Skylark application.
   - Otherwise it's Python

**Comment by creachadair** [comment]
> Sounds good to me, but I'm not the leader of the language analysis team hehe

I'm just trying to understand the parameters of the request. I'm a little bit reluctant to bake fragile heuristics into a very general classifier, unless it's pretty harmless. For Babelfish, the question "what language is this text?" really means "what does the syntax look like?" for which the distinction between S(tar|ky)lark isn't important—and in fact probably distracting unless we teach the drivers to negotiate for custody. For UI tools, however, it may be more important to distinguish.

It's possible a better solution is to identify an idea of "dialects", where two dialects share a syntax but have different embeddings (e.g., browser JS vs. Node JS, WoW Lua vs. SQL UDF Lua, Starkylark vs. Python, etc.). Then a classification may consist of one _language_ and zero or more _dialects_, which might help. 

That's a much bigger task, however, so for now I'm just trying to get a sense of how much impact that work might have. If the analysis like the one you described above could work around the problem with some filename heuristics, it's not necessary to create a new scheme.

**Comment by bzz** [comment]
> This mistake is also done by linguist, as shown here

as Enry right now just mirrors the Linguist - I would say everything works as expected and issue belongs to Linguist upstream or the umbrella issue where we track those on our side https://github.com/src-d/enry/issues/181

@creachadair 
>  I'm a little bit reluctant to bake fragile heuristics into a very general classifier, unless it's pretty harmless.

Well, so far we did not bake any heuristics to Enry at all, on top of what is in upstream's Linguist and there was no discussion that I'm aware of about changing this approach.

That being said, I would be happy to address this and the rest of the https://github.com/src-d/enry/issues/181 in the Linguist upstream, as soon as we agree 
 - to follow this approach, as we did so far
 - priority of this work


-----------

On
> For Babelfish, the question "what language is this text?" really means "what does the syntax look like?" 

I would suggest keeping the separation of responsibility between Enry (linguist clone in Go) and Bblfsh: there already is a discussion on a new feature - dialect support on bblfsh side (alas, not moved to a proper place in SDK yet) https://github.com/bblfsh/bash-driver/issues/39#issuecomment-442539768

**Comment by campoy** [comment]
I'm totally fine with this not being solved for now.

It's definitely an interesting thing to take into account in the future, whether different dialects can be detected easily and whether it's worth the effort.

Thanks for the info!

**Comment by bzz** [comment]
Will close for now, if there is no further discussion but please feel free to re-open if something is not clear, etc.
