### ISSUE TITLE
T-SQL support

### ISSUE THREAD

**Issue by codeFather2** [src-d/enry#200]
Hello. Is it real to add support for detection T-sql scripts? Are there any reasons why this support is still not there, maybe there are some problems with which help is needed?

**Comment by smola** [comment]
enry is a Go port of github/linguist. We (try to) match exactly what linguist supports.

You can file a requedt at linguist: https://github.com/github/linguist

**Comment by bzz** [comment]
As @smola noted - such requests/contribution should be made in Linguist upstream, see [CONTRIBUTING.md#adding-an-extension-to-a-language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).

Going to close this one in favor of #181 where we aggregate suggestions and as the question seems to be answered.

But please, feel free to re-open in case something is not clear, etc!
