### ISSUE TITLE
enry - linguist single file report logic mismatch

### ISSUE THREAD

**Issue by EgorBu** [src-d/enry#216]
There seems to be a logic mismatch between `enry` and `linguist` on a single file report  - 
`enry` & `linguist` skip vendored files for a `dir` but in case of a single file:
 -  `linguist` returns information [if this file is vendored](https://github.com/github/linguist/blob/master/bin/github-linguist#L73)
 - `enry` doesn't

**Comment by bzz** [comment]
@EgorBu thank you for a great find!

Could you plz confirm if something like

```
$  ./enry -json regex/oniguruma.go | jq .
{
  "filename": "oniguruma.go",
  "language": "Go",
  "lines": 12,
  "mime": "text/x-go",
  "total_lines": 17,
  "type": "Text",
  "vendored": false
}

$ enry -json ~/go/src/github.com/bblfsh/bblfshd/vendor/golang.org/x/crypto/AUTHORS | jq .
{
  "filename": "AUTHORS",
  "language": "",
  "lines": 3,
  "mime": "text/plain",
  "total_lines": 3,
  "type": "Text",
  "vendored": true
}

$ enry ~/go/src/github.com/bblfsh/bblfshd/vendor/golang.org/x/crypto/AUTHORS
AUTHORS: 3 lines (3 sloc)
  type:      Text
  mime_type: text/plain
  language:
  vendored:  true

$ enry regex/oniguruma.go
oniguruma.go: 17 lines (12 sloc)
  type:      Text
  mime_type: text/x-go
  language:  Go
  vendored:  false
```

would work for you?

**Comment by EgorBu** [comment]
yes, it will work for me! I will work with `json` if it's important, thank you!

**Comment by bzz** [comment]
It's on master now, planing to cut a new release as soon as as the [last issue is closed](https://github.com/src-d/enry/milestone/2)
