### ISSUE TITLE
Reports gitignore as vendor

### ISSUE THREAD

**Issue by erizocosmico** [src-d/enry#229]
Enry says `.gitignore` is vendor, but shouldn't be. Is that intentional?

```go
fmt.Println(enry.IsVendor(".gitignore")) // output: true
```

**Comment by bzz** [comment]
@erizocosmico thank you for spotting - that seems like a bug as [according to linguist](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L271) that should be a vendor.

**Comment by bzz** [comment]
@erizocosmico sorry, I somehow has initially miss-read the question, adding a negation 🤦‍♂ .

> Enry says .gitignore is vendor

Yes, it supposed to be that way, as that's what [Linguist](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L271) has [defined](https://github.com/github/linguist/blob/d4a975d342a89227678ccebe475f45917d46e1b1/test/test_file_blob.rb#L346) 4 years ago.

Updated the answer above and will be closing, if that answers the questions.
