### ISSUE TITLE
import is a program, not an importable package

### ISSUE THREAD

**Issue by 4ndre4s** [src-d/enry#239]
This is my code: 
```
package main

import (
	"github.com/src-d/enry/cmd/enry"
)

func main() {
	lang, safe := enry.GetLanguageByExtension("foo.go")
}
```
When I run `go get`, I get the following error:
`package github.com/src-d/enry/cmd/enry: import "github.com/src-d/enry/cmd/enry" is a program, not an importable package`

**Comment by creachadair** [comment]
The trouble is that you're importing the command-line tool, rather than the library. Please try using the import path `"github.com/src-d/enry/v2"` instead, e.g., https://play.golang.org/p/qs07S_cvkbT

**Comment by 4ndre4s** [comment]
I thought so too, but in the documentary the installation was directly before the use in go, so it seemed plausible to me. Thanks, I'll check tomorrow.

**Comment by creachadair** [comment]
It sounds like we could improve the documentation examples a bit, thanks for pointing that out.

**Comment by creachadair** [comment]
I've updated the README to add some more detail, so I'll close this—but if you still have issues please feel free to re-open it.
