### ISSUE TITLE
Clarify installation instruction

### ISSUE THREAD

**Issue by cup** [src-d/enry#243]
~~~
(cd /tmp; go get github.com/src-d/enry/v2/cmd/enry)
~~~

https://github.com/src-d/enry#installation

This is misleading, as it assumes the user has already done

~~~
go mod init hello-world
~~~

or similar. If not, it will fail with:

~~~
package github.com/src-d/enry/v2/cmd/enry: cannot find package
"github.com/src-d/enry/v2/cmd/enry"
~~~

**Comment by cup** [comment]
https://github.com/src-d/enry/issues/241

**Comment by creachadair** [comment]
Thanks for the report. The latest Go release changed the default behaviour again, so we'll have to update the instructions. I'll take care of it on Monday.
