### ISSUE TITLE
Get color from "parent language" if there is no definition for the language itself

### ISSUE THREAD

**Issue by alexanderadam** [src-d/enry#252]
I opened this issue because of [a corresponding issue in gitea](https://github.com/go-gitea/gitea/issues/10476).

Gitea uses enry for the language bar and some colors can't be fetched.

IMHO Linguist uses groups for this and properties are inherited from the parent group. For example [Haml inherits from HTML](https://github.com/github/linguist/blob/96ca71ab99c2f9928d5d69f4c08fd2a51440d045/lib/linguist/languages.yml#L2089-L2090).

So I guess it would help if the color mapping would work similar.

**PS:** Just some examples to point out what it looks like in gitea:

![Screenshot_20200226_140920](https://user-images.githubusercontent.com/372620/75347772-ccf7eb00-58a1-11ea-8f5c-e3513d35654b.png)

![Screenshot_20200226_141331](https://user-images.githubusercontent.com/372620/75347956-2fe98200-58a2-11ea-8266-7798a52efab0.png)

**Comment by lunny** [comment]
Maybe @mcuadros would like also to move this project to go-git organization?

**Comment by bzz** [comment]
That would be a simple change to the https://github.com/src-d/enry/blob/697929e1498cbdb7726a4d3bf4c48e706ee8c967/utils.go#L78 if group information would have been stored somewhere in the `data` generated from .yml

**Comment by lafriks** [comment]
when enry is hard forked to go-enry organization I could probably implement this

**Comment by bzz** [comment]
JFYI I'm not related to the plans of forking enry to a separate org. 

Meanwhile I have just pushed a https://pkg.go.dev/github.com/bzz/enry/v2 and will be happy to assist adding this feature, if needed.

**Comment by bzz** [comment]
This has been implemented by @lafriks and is included in latest https://github.com/go-enry/go-enry/releases/tag/v2.3.0

**Comment by alexanderadam** [comment]
Awesome, thank you folks!
