### ISSUE TITLE
cli: add --json flag with output compatible with github/linguist

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/enry#39]
`github/linguist` CLI has `--json` cmdline arg to output the result in JSON. it prints in a human readable format otherwise. We need to be consistent because enry must be a drop-in replacement.

**Comment by smola** [comment]
Note that enry does not aim to be a drop-in replacement for `github/linguist` CLI. There is functionality that we might avoid, such as working with git repositories.

It's a desirable property though and adding `--json` flag with compatible output would be good.

**Comment by vmarkovtsev** [comment]
Currently, `github/linguist` has only [two cmdline args](https://github.com/github/linguist/blob/master/bin/linguist#L23). We used to follow `--json` but somehow removed it.

So it is pretty possible to be cmdline compatible, and nothing difficult in even implementing `--breakdown` (not in this issue though).

The thing is that I am using `enry` as a drop-in replacement which prints JSON and really don't want to maintain two separate branches.

**Comment by bzz** [comment]
As a user, I'd like to have `--json` in CLI for interoperability with my other tools.
Behavior similar to `--breakdown` would nice to have later on.

**Comment by smola** [comment]
Fixed https://github.com/src-d/enry/pull/41
