### ISSUE TITLE
enry /path --json misbehaves

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/enry#62]
`enry /path --json` does not output json, e.g.:

```
94.44%	Python
5.56%	Text
```

**Comment by mcarmonaa** [comment]
```
$ enry -help
enry, A simple (and faster) implementation of github/linguist 
usage: enry <path>
       enry [-json] [-breakdown] <path>
       enry [-json] [-breakdown]
```

flag use only one dash and it should be before the path

**Comment by vmarkovtsev** [comment]
`linguist` demands that the flags are always after the path and with two dashes. Please make the interface conforming, otherwise, we cannot drop-replace linguist. I do understand that the Go standard parser works this way, but that's the programmer's problem.

**Comment by abeaumont** [comment]
@vmarkovtsev according to @mcuadros having a drop-in replacement for `linguist` is not a goal. Closing it.

**Comment by vmarkovtsev** [comment]
Edit: this is *strictly* forbidden.

**Comment by abeaumont** [comment]
@vmarkovtsev what are you referring to?

**Comment by vmarkovtsev** [comment]
The private chat on Slack which happened today :wink:

**Comment by abeaumont** [comment]
@vmarkovtsev right, I explicitely said in that conversation that this would be the proper place for that discussion, but it didn't happen.
