### ISSUE TITLE
release should attach a binary distribution for linux and osx

### ISSUE THREAD

**Issue by mcuadros** [src-d/enry#74]
In order to be easy to install and use enry, we should provide a precompiled version of it, for linux and osx.

**Comment by vmarkovtsev** [comment]
Any updates on this?

**Comment by abeaumont** [comment]
@vmarkovtsev we lack the correct github token to make this work. CC: @mcuadros.

**Comment by marnovo** [comment]
@mcuadros also need a token. Same as last one.

**Comment by vmarkovtsev** [comment]
Cool! Where do I take them now?

**Comment by abeaumont** [comment]
The fix didn't work, will look at why.

**Comment by abeaumont** [comment]
It seems it was a token permission problem, it works now.
