### ISSUE TITLE
add and publish shared library libenry.so

### ISSUE THREAD

**Issue by smola** [src-d/enry#89]
We would like to call enry from code in the JVM. In order to do that, we need enry compiled as a shared library.

**Comment by erizocosmico** [comment]
@smola Do we want to keep the exported definitions and the logic of publishing the shared libraries here or in enry-java? For now, I have them on `enry-java`, but will move them here if needed.

**Comment by erizocosmico** [comment]
Done between #91 and #92

**Comment by bzz** [comment]
@abeaumont AFAIK we can close this after #94

**Comment by abeaumont** [comment]
thanks @bzz !
