### ISSUE TITLE
skip binary files (Bogus Modelica detection)

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/enry#9]
django/djnago project: *.mo files are recognized as Modelica but are really some homebrew localization format.

**Comment by smola** [comment]
github/linguist returns no language for these, since they ignore every binary file:

```
  def detect(blob, allow_empty: false)
    # Bail early if the blob is binary or empty.
    return nil if blob.likely_binary? || blob.binary? || (!allow_empty && blob.empty?)
```

**Comment by mcarmonaa** [comment]
done https://github.com/src-d/enry/pull/59
